name: makerware # you probably want to 'snapcraft register <name>'
version: '3.9.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: MakerBot makerware
description: |
  MakerBot makerware is the slicing and host program for MakerBot 3D
  printers.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  makerware:
    command: desktop-launch makerware --socket=unix:/tmp/conveyord.socket
    plugs:
      - home
      - network
      - x11
      - gsettings
      - opengl
      - raw-usb
      - browser-support
    desktop: usr/share/applications/makerware.desktop

  digitizer:
    command: desktop-launch digitizer --socket=unix:/tmp/conveyord.socket
    plugs:
      - home
      - network
      - x11
      - gsettings
      - opengl
      - raw-usb
      - pulseaudio
      - alsa
      - camera
      - browser-support
    desktop: usr/share/applications/digitizer.desktop

  conveyor:
    daemon: simple
    command: env LD_LIBRARY_PATH=$SNAP/usr/lib/makerbot:$LD_LIBRARY_PATH conveyor-svc --config $SNAP/etc/conveyor.conf
    plugs:
      - home
      - network
      - network-bind
      - gsettings
      - raw-usb
      - camera

  zenity:
    command: zenity
    plugs:
      - home
      - network
      - x11
      - gsettings
      - opengl

parts:
  base:
    plugin: nil
    after:
      - desktop-qt5

  makerware:
    plugin: nil
    stage-packages:
      - makerware
      - libqt5opengl5
      - libqt5webkit5
      - libqt5multimediawidgets5
      - libopencv2.4-jni
      - libyajl2
      - libpulse0
      - zenity
    after:
      - base
    organize:
      etc/conveyor.conf: etc/conveyor.conf.makerware.snap
      usr/bin/makerware: usr/bin/makerware.makerware.snap
      usr/bin/digitizer: usr/bin/digitizer.makerware.snap
      usr/bin/zenity: usr/bin/zenity.makerware.snap

  zenity:
    plugin: autotools
    source: https://download.gnome.org/sources/zenity/3.18/zenity-3.18.1.1.tar.xz
    configflags:
      - --datarootdir=/snap/makerware/current/usr/share
    build-packages:
      - gnome-pkg-tools
      - gnome-common
      - yelp-tools
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libnotify-dev
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libgtk-3-bin
    after:
      - makerware
    organize:
      bin/zenity: usr/bin/zenity

  local:
    source: ./local
    plugin: dump
    after:
      - makerware
    organize:
      conveyor.conf: etc/conveyor.conf
      makerware: usr/bin/makerware
      digitizer: usr/bin/digitizer
